{% set version = '1.0-27' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sgeostat
  version: {{ version|replace("-", "_") }}

source:
  fn: sgeostat_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/sgeostat_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/sgeostat/sgeostat_{{ version }}.tar.gz
  sha256: 6b930d09901be3a80368b3b23127b4bd15565a4834a851100cfb2e34a5b809c7

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  skip: True  # [win32]

requirements:
  build:
    - posix                # [win]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('sgeostat')"  # [not win]
    - "\"%R%\" -e \"library('sgeostat')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=sgeostat
  license: GPL (>= 2)
  summary: An Object-oriented Framework for Geostatistical Modeling in S+ containing functions
    for variogram estimation, variogram fitting and kriging as well as some plot functions.
    Written entirely in S, therefore works only for small data sets in acceptable computing
    time.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
