appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: GNT8tSBoRjDjbvoaeI82hyPoY3Wmmp9pOzoRBeno4XO4j4ylIaqmwp4x9LgAmRd8/HPhBssYYVw4ThY+F3cmQ9OVBeksAJFxSdGQ3oo+DIg2IS0AMmKzv3VqJBx2RlNNpgnHCH9/Yv0cohJUsepbREB9RUpOaHwA2aFX1D6NsNzWGII/2Vwi7gbRLELZzZse6oBJJe82oH8VrS6qVNY9uU5qYJcH+VOy/0roeb8CwCETCC6DeyhYRu7JlTaJqR9LH3m4HJmf9dZkPUmvm7renMfQDrfeAbn93vaJpLfD1ho70niYZoOhUhXGFDeP2O6qqy/f7HyGUIwetARekbfnW+W+E631ihf8H1SNPX8vi+gb7ihkj+rJCcdY8/IMCaDNfyqUeO5vmA1MKi3dYQlNBOUgfG9CgjxAR4AYLPPj2nUX3mWpy0LKX4wgAavJ9gJusRBSGGLDlPJAAUFAlFdonfhhGFwsSKVZMTXV3n1wEXgucmPjA8JUOOLpm1k6EkBdPLsAsGPIq7HFjYE013YGgsC0rXFr48um4DwFaNefjxkM4yY9mSvWv7vVtzNDZxn+CCfgOZalk59BamPe+3vF19G8mNqtmWeiCCoEJxvTE7z+NwZOVtnG4+uijnbd5bsFopWV7jgDL0WlhbfT1Wy2A98DhPFx8B0MmbKQTzKEjFY=}
bot:
  automerge: true
